<?php

$labels['externalaccounts'] = 'Externa konton';
$labels['editexternalaccounts'] = 'Ändra externa konton';
$labels['editexternalaccount'] = 'Ändra externt konto';
$labels['editexternalaccountfromtitle'] = 'Ändringsformulär för externt konto';

$labels['newexternalaccount'] = 'Nytt externt konto';
$labels['disabled'] = 'Avaktiverad';
$labels['downloadnewmail'] = 'Ladda ner nya e-mejl';

$labels['externalaccountsettings'] = 'Externt kontoinställningar';
$labels['enabled'] = 'Aktiv';
$labels['name'] = 'Namn';
$labels['serverinformation'] = 'Serverinformation';
$labels['type'] = 'Typ';
$labels['serveraddress'] = 'Serveradress';
$labels['tcp/ipport'] = 'TCP/IP port';
$labels['connectionsecurity'] = 'Anslutningssäkerhet';
$labels['none'] = 'Inget';
$labels['starttlsrequired'] = 'STARTTLS (Krävs)';
$labels['ssl/tls'] = 'SSL/TLS';
//$labels['username'] = 'Användarnamn';
//$labels['password'] = 'Lösenord';
//$labels['settings'] = 'Inställningar';
$labels['minutesbetweendownload'] = 'Minuter mellan nerladdning';
$labels['delivertorecipientsinmimeheaders'] = 'Leverera till mottagare i MIME headers';
$labels['retrievedatefromreceivedheader'] = 'Läs datum från Received-header';
$labels['antispam'] = 'Antispam';
$labels['antivirus'] = 'Anti-virus';
$labels['allowrouterecipients'] = 'Tillåt leverans till rutt';
$labels['deletemessagesimmediately'] = 'Radera meddelanden omedelbart';
$labels['donotdeletemessages'] = 'Ta inte bort meddelanden';
$labels['deletemessagesafter'] = 'Ta bort meddelanden efter';
$labels['days'] = 'dagar';


$messages['externalaccountsuccessfullyupdated'] = 'Externt konto har uppdaterats.';
$messages['externalaccountnowdownloading'] = 'Laddar ner från externt konto';
$messages['externalaccountdeleteconfirm'] = 'Vill du verkligen ta bort markerat externt konto?';

$messages['internalerror'] = 'Fel uppstod i vald åtgärd.';
//$messages['connecterror'] = $messages['internalerror'] . ' Anslutningsfel.';
$messages['loaderror'] = 'Det gick inte att ladda externt konto/externa konton.';
$messages['loadconnecterror'] = $messages['loaderror'] . ' Anslutningsfel.';
$messages['updateerror'] = 'Det gick inte att uppdatera externt konto.';
$messages['updateconnecterror'] = $messages['updateerror'] . ' Anslutningsfel.';

